export const metadata = {
    title: "About us",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <div>
            {children}
        </div>
    );
}