"use client"
import "bootstrap/dist/css/bootstrap.min.css"
import "./css/globals.css"

import Footer from "./componentes/HomeComponent/Footer"
import Header from "./componentes/HomeComponent/Header"
import { useEffect, useState } from "react"
import AosWrapper from "./componentes/AOSWrapper "
import IntroScreenLoading from "./componentes/IntroScreenLoading"

// export const metadata = {
//   title: "الصفحة الرئيسية",
//   description: "Generated by create next app",
//   icons: [
//     { rel: "icon", url: "/img/IconSite.svg", sizes: "32x32" },
//     { rel: "icon", url: "/img/IconSite.svg", sizes: "64x64" }
//   ]
// }

export default function RootLayout({ children }) {
  const [showIntro, setShowIntro] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setShowIntro(false);
    }, 5000);

    return () => clearTimeout(timer);
  }, []);

  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min.js")
  }, [])
  return (
    <html lang="ar" dir="rtl">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        {showIntro ? <IntroScreenLoading /> :
      <AosWrapper >
        < Header />
        {children}
        <Footer />
      </AosWrapper>}
      </body>
    </html>
  )
}
