
import { icon } from "@fortawesome/fontawesome-svg-core";
import HomeLayout from "./Homepage/layout";


export const metadata = {
  title: "الصفحة الرئيسية",
  description: "Generated by create next app",
  icons: [
    { rel: "icon", url: "/img/IconSite.svg", sizes: "32x32" },
    { rel: "icon", url: "/img/IconSite.svg", sizes: "64x64" },
  ]
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body>
        <HomeLayout>{children}</HomeLayout>
      </body>
    </html>
  );
}
